### ISSUE TITLE
Looking for maintainers?

### ISSUE THREAD

**Issue by contolini** [angular/protractor-accessibility-plugin#10]
Hey @sjelin and @juliemr, are y'all looking for help maintaining this plugin? I'd love to help out. We use it across our projects (https://github.com/cfpb) and have a vested interest in building it out.

**Comment by sjelin** [comment]
Hey, sorry, this feel out of the list of places I check for notifications.  I'll try to be more prompt in the future.  Feel free to keep posting PRs!

**Comment by sjelin** [comment]
Just did a version bump with your changes last Friday btw!
